In [4]:
import pandas
import numpy

url_xtrain_csv = 'https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/X_train.csv'
url_ytrain_csv = 'https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/y_train.csv'
url_info_csv = 'https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/studs_info.csv'
url_exams_csv = 'https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/zachety.csv'

xtrain_csv = pandas.read_csv(url_xtrain_csv)
ytrain_csv = pandas.read_csv(url_ytrain_csv)
info_csv = pandas.read_csv(url_info_csv)
exams_csv = pandas.read_csv(url_exams_csv)

In [5]:
#1 задание

print(xtrain_csv.shape, ytrain_csv.shape, info_csv.shape, exams_csv.shape)

(105058, 8) (105058, 2) (5466, 13) (133223, 8)

In [6]:
#2 задание

xytrain = pandas.concat([xtrain_csv, ytrain_csv],axis=1)
xytrain

,Unnamed: 0,STD_ID,НАПРАВЛЕНИЕ,ГОД,КУРС,СЕМЕСТР,АТТЕСТАЦИЯ,ДИСЦИПЛИНА,index,mark
0,51081,175711,38.03.02 Менеджмент,2018-2019,2.0,4.0,Экзамен,Маркетинг,51081,5
1,72921,100647,31.05.01 Лечебное дело,2015-2016,3.0,5.0,Экзамен,"Пропедевтика внутренних болезней, лучевая диаг...",72921,5
2,96438,199311,31.05.03 Стоматология,2019-2020,1.0,1.0,Экзамен,Химия,96438,5
3,273044,162002,38.03.02 Менеджмент,2017-2018,2.0,3.0,Экзамен,Статистика,273044,4
4,371309,108384,31.05.01 Лечебное дело,2018-2019,5.0,9.0,Экзамен,Педиатрия,371309,3
...,...,...,...,...,...,...,...,...,...,...
105053,224856,176141,40.03.01 Юриспруденция,2017-2018,1.0,2.0,Курсовая работа,Конституционное право,224856,3
105054,260998,182794,31.05.01 Лечебное дело,2018-2019,2.0,4.0,Экзамен,Нормальная физиология,260998,3
105055,57245,162391,31.05.01 Лечебное дело,2016-2017,1.0,2.0,Дифференцированный зачет,Иностранный язык,57245,4
105056,218529,202479,38.03.01 Экономика,2017-2018,1.0,1.0,Дифференцированный зачет,Информатика,218529,4
105057,233318,182325,08.03.01 Строительство,2018-2019,2.0,3.0,Курсовая работа,Технологические процессы в строительстве,233318,4

In [9]:
#3 задание

info_csv.isna().sum().sum()

5822

In [10]:
#4 задание

print(xytrain['АТТЕСТАЦИЯ'].unique())
print(xytrain['АТТЕСТАЦИЯ'].value_counts())

['Экзамен' 'Курсовая работа' 'Дифференцированный зачет' 'Курсовой проект'
 'Зачет']
Экзамен                     60092
Дифференцированный зачет    37791
Курсовая работа              5522
Курсовой проект              1631
Зачет                          22
Name: АТТЕСТАЦИЯ, dtype: int64

In [11]:
#5 задание

xytrain.columns = [i.lower() for i in xytrain.columns]
xytrain

,unnamed: 0,std_id,направление,год,курс,семестр,аттестация,дисциплина,index,mark
0,51081,175711,38.03.02 Менеджмент,2018-2019,2.0,4.0,Экзамен,Маркетинг,51081,5
1,72921,100647,31.05.01 Лечебное дело,2015-2016,3.0,5.0,Экзамен,"Пропедевтика внутренних болезней, лучевая диаг...",72921,5
2,96438,199311,31.05.03 Стоматология,2019-2020,1.0,1.0,Экзамен,Химия,96438,5
3,273044,162002,38.03.02 Менеджмент,2017-2018,2.0,3.0,Экзамен,Статистика,273044,4
4,371309,108384,31.05.01 Лечебное дело,2018-2019,5.0,9.0,Экзамен,Педиатрия,371309,3
...,...,...,...,...,...,...,...,...,...,...
105053,224856,176141,40.03.01 Юриспруденция,2017-2018,1.0,2.0,Курсовая работа,Конституционное право,224856,3
105054,260998,182794,31.05.01 Лечебное дело,2018-2019,2.0,4.0,Экзамен,Нормальная физиология,260998,3
105055,57245,162391,31.05.01 Лечебное дело,2016-2017,1.0,2.0,Дифференцированный зачет,Иностранный язык,57245,4
105056,218529,202479,38.03.01 Экономика,2017-2018,1.0,1.0,Дифференцированный зачет,Информатика,218529,4
105057,233318,182325,08.03.01 Строительство,2018-2019,2.0,3.0,Курсовая работа,Технологические процессы в строительстве,233318,4

In [12]:
#6 задание

dc = {'Код направления':[],'Название направления': []}
for i in range(xytrain.shape[0]):
    code, name = map(str, str(xytrain.iloc[i][2]).split(maxsplit=1))
    dc['Код направления'].append(ConnectionRefusedError)
    dc['Название направления'].append(name)

df = pandas.DataFrame(dc)
xytrain = pandas.concat([xytrain,df],axis=1)
xytrain.drop(['направление'],axis=1,inplace=True)

xytrain

,unnamed: 0,std_id,год,курс,семестр,аттестация,дисциплина,index,mark,Код направления,Название направления
0,51081,175711,2018-2019,2.0,4.0,Экзамен,Маркетинг,51081,5,<class 'ConnectionRefusedError'>,Менеджмент
1,72921,100647,2015-2016,3.0,5.0,Экзамен,"Пропедевтика внутренних болезней, лучевая диаг...",72921,5,<class 'ConnectionRefusedError'>,Лечебное дело
2,96438,199311,2019-2020,1.0,1.0,Экзамен,Химия,96438,5,<class 'ConnectionRefusedError'>,Стоматология
3,273044,162002,2017-2018,2.0,3.0,Экзамен,Статистика,273044,4,<class 'ConnectionRefusedError'>,Менеджмент
4,371309,108384,2018-2019,5.0,9.0,Экзамен,Педиатрия,371309,3,<class 'ConnectionRefusedError'>,Лечебное дело
...,...,...,...,...,...,...,...,...,...,...,...
105053,224856,176141,2017-2018,1.0,2.0,Курсовая работа,Конституционное право,224856,3,<class 'ConnectionRefusedError'>,Юриспруденция
105054,260998,182794,2018-2019,2.0,4.0,Экзамен,Нормальная физиология,260998,3,<class 'ConnectionRefusedError'>,Лечебное дело
105055,57245,162391,2016-2017,1.0,2.0,Дифференцированный зачет,Иностранный язык,57245,4,<class 'ConnectionRefusedError'>,Лечебное дело
105056,218529,202479,2017-2018,1.0,1.0,Дифференцированный зачет,Информатика,218529,4,<class 'ConnectionRefusedError'>,Экономика
105057,233318,182325,2018-2019,2.0,3.0,Курсовая работа,Технологические процессы в строительстве,233318,4,<class 'ConnectionRefusedError'>,Строительство

In [15]:
#8 задание

d = {'Пол': []}
for i in range(info_csv.shape[0]):
  d['Пол'].append(0  if (info_csv.loc[i]['Пол']=='М') else  1)

studs_info_csv_intGender = pandas.DataFrame(d)

info_csv.drop(['Пол'], axis=1, inplace=True)
info_csv = pandas.concat([info_csv,studs_info_csv_intGender],axis=1)
info_csv

,STD_ID,number,Статус,Дата выпуска,Категория обучения,Форма обучения,Шифр,направление (специальность),,Образование,Дата выдачи,Что именно закончил,Пол
0,99136,13951.0,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2629.0,СР,2013-06-26 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,1
1,99112,13998.0,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,8240.0,СР,2012-06-23 00:00:00,"МОУ СОШ N 2, ПЕСТОВО",1
2,99109,13999.0,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2314.0,СР,2013-06-25 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,1
3,99125,13953.0,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2345.0,СР,2013-06-23 00:00:00,"Гимназия ""ГАРМОНИЯ""",1
4,100676,13950.0,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2650.0,СР,2012-06-29 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5461,100678,978.0,СТ,NaN,БП,Д,31.05.01,Лечебное дело,2388.0,СР,2013-06-21 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,1
5462,100663,1021.0,СТ,NaN,ДОГ,Д,31.05.01,Лечебное дело,2554.0,СР,2013-06-27 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,1
5463,191630,6447.0,СТ,NaN,ДОГ,Д,31.05.01,Лечебное дело,6692.0,СР,2014-05-31 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,1
5464,191625,3765.0,СТ,NaN,ДОГ,Д,31.05.01,Лечебное дело,NaN,NaN,NaN,NaN,1
5465,194978,5245.0,СТ,NaN,ДОГ,Д,31.05.01,Лечебное дело,NaN,NaN,NaN,NaN,1

In [14]:
#9 задание

inf_ekz = xytrain[xytrain['дисциплина']=='Информатика'][xytrain['аттестация']=='Экзамен']
print(inf_ekz.shape[0], inf_ekz['mark'].sum()/inf_ekz.shape[0])

60 4.6

<ipython-input-14-90fa1ff06a4b>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  inf_ekz = xytrain[xytrain['дисциплина']=='Информатика'][xytrain['аттестация']=='Экзамен']