In [165]:
import pandas
import numpy

url_x_train_csv = 'https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/X_train.csv'
url_y_train_csv = 'https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/y_train.csv'
url_studs_info_csv = 'https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/studs_info.csv'
url_zachety_csv = 'https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/zachety.csv'

x_train_csv = pandas.read_csv(url_x_train_csv)
y_train_csv = pandas.read_csv(url_y_train_csv)
studs_info_csv = pandas.read_csv(url_studs_info_csv)
zachety_csv = pandas.read_csv(url_zachety_csv)

In [4]:
# 1

print(x_train_csv.shape, y_train_csv.shape, studs_info_csv.shape, zachety_csv.shape)

(105058, 8) (105058, 2) (5466, 13) (133223, 8)

In [56]:
# 2

train = pandas.concat([x_train_csv, y_train_csv],axis=1)
train

,Unnamed: 0,STD_ID,НАПРАВЛЕНИЕ,ГОД,КУРС,СЕМЕСТР,АТТЕСТАЦИЯ,ДИСЦИПЛИНА,index,mark
0,51081,175711,38.03.02 Менеджмент,2018-2019,2.0,4.0,Экзамен,Маркетинг,51081,5
1,72921,100647,31.05.01 Лечебное дело,2015-2016,3.0,5.0,Экзамен,"Пропедевтика внутренних болезней, лучевая диаг...",72921,5
2,96438,199311,31.05.03 Стоматология,2019-2020,1.0,1.0,Экзамен,Химия,96438,5
3,273044,162002,38.03.02 Менеджмент,2017-2018,2.0,3.0,Экзамен,Статистика,273044,4
4,371309,108384,31.05.01 Лечебное дело,2018-2019,5.0,9.0,Экзамен,Педиатрия,371309,3
...,...,...,...,...,...,...,...,...,...,...
105053,224856,176141,40.03.01 Юриспруденция,2017-2018,1.0,2.0,Курсовая работа,Конституционное право,224856,3
105054,260998,182794,31.05.01 Лечебное дело,2018-2019,2.0,4.0,Экзамен,Нормальная физиология,260998,3
105055,57245,162391,31.05.01 Лечебное дело,2016-2017,1.0,2.0,Дифференцированный зачет,Иностранный язык,57245,4
105056,218529,202479,38.03.01 Экономика,2017-2018,1.0,1.0,Дифференцированный зачет,Информатика,218529,4
105057,233318,182325,08.03.01 Строительство,2018-2019,2.0,3.0,Курсовая работа,Технологические процессы в строительстве,233318,4

In [6]:
# 3

studs_info_csv.isna().sum().sum()

5822

In [7]:
# 4

print(x_train_csv['АТТЕСТАЦИЯ'].unique())
print(x_train_csv['АТТЕСТАЦИЯ'].value_counts())

['Экзамен' 'Курсовая работа' 'Дифференцированный зачет' 'Курсовой проект'
 'Зачет']
Экзамен                     60092
Дифференцированный зачет    37791
Курсовая работа              5522
Курсовой проект              1631
Зачет                          22
Name: АТТЕСТАЦИЯ, dtype: int64

In [57]:
# 5

train.columns = [i.lower() for i in train.columns]
train

,unnamed: 0,std_id,направление,год,курс,семестр,аттестация,дисциплина,index,mark
0,51081,175711,38.03.02 Менеджмент,2018-2019,2.0,4.0,Экзамен,Маркетинг,51081,5
1,72921,100647,31.05.01 Лечебное дело,2015-2016,3.0,5.0,Экзамен,"Пропедевтика внутренних болезней, лучевая диаг...",72921,5
2,96438,199311,31.05.03 Стоматология,2019-2020,1.0,1.0,Экзамен,Химия,96438,5
3,273044,162002,38.03.02 Менеджмент,2017-2018,2.0,3.0,Экзамен,Статистика,273044,4
4,371309,108384,31.05.01 Лечебное дело,2018-2019,5.0,9.0,Экзамен,Педиатрия,371309,3
...,...,...,...,...,...,...,...,...,...,...
105053,224856,176141,40.03.01 Юриспруденция,2017-2018,1.0,2.0,Курсовая работа,Конституционное право,224856,3
105054,260998,182794,31.05.01 Лечебное дело,2018-2019,2.0,4.0,Экзамен,Нормальная физиология,260998,3
105055,57245,162391,31.05.01 Лечебное дело,2016-2017,1.0,2.0,Дифференцированный зачет,Иностранный язык,57245,4
105056,218529,202479,38.03.01 Экономика,2017-2018,1.0,1.0,Дифференцированный зачет,Информатика,218529,4
105057,233318,182325,08.03.01 Строительство,2018-2019,2.0,3.0,Курсовая работа,Технологические процессы в строительстве,233318,4

In [58]:
# 6

dc = {'Код направления':[],'Название направления': []}
for i in range(train.shape[0]):
    kod, nazv = map(str, str(train.iloc[i][2]).split(maxsplit=1))
    dc['Код направления'].append(kod)
    dc['Название направления'].append(nazv)

df = pandas.DataFrame(dc)
train = pandas.concat([train,df],axis=1)
train.drop(['направление'],axis=1,inplace=True)

train

,unnamed: 0,std_id,год,курс,семестр,аттестация,дисциплина,index,mark,Код направления,Название направления
0,51081,175711,2018-2019,2.0,4.0,Экзамен,Маркетинг,51081,5,38.03.02,Менеджмент
1,72921,100647,2015-2016,3.0,5.0,Экзамен,"Пропедевтика внутренних болезней, лучевая диаг...",72921,5,31.05.01,Лечебное дело
2,96438,199311,2019-2020,1.0,1.0,Экзамен,Химия,96438,5,31.05.03,Стоматология
3,273044,162002,2017-2018,2.0,3.0,Экзамен,Статистика,273044,4,38.03.02,Менеджмент
4,371309,108384,2018-2019,5.0,9.0,Экзамен,Педиатрия,371309,3,31.05.01,Лечебное дело
...,...,...,...,...,...,...,...,...,...,...,...
105053,224856,176141,2017-2018,1.0,2.0,Курсовая работа,Конституционное право,224856,3,40.03.01,Юриспруденция
105054,260998,182794,2018-2019,2.0,4.0,Экзамен,Нормальная физиология,260998,3,31.05.01,Лечебное дело
105055,57245,162391,2016-2017,1.0,2.0,Дифференцированный зачет,Иностранный язык,57245,4,31.05.01,Лечебное дело
105056,218529,202479,2017-2018,1.0,1.0,Дифференцированный зачет,Информатика,218529,4,38.03.01,Экономика
105057,233318,182325,2018-2019,2.0,3.0,Курсовая работа,Технологические процессы в строительстве,233318,4,08.03.01,Строительство

In [125]:
# 7

std_id_male = studs_info_csv[studs_info_csv['Пол'] == 'М']['STD_ID'].values
train_male_3year = train[train['std_id'].isin(std_id_male) == True][train['курс'] == 3]
train_male_3year

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  after removing the cwd from sys.path.

,unnamed: 0,std_id,год,курс,семестр,аттестация,дисциплина,index,mark,Код направления,Название направления
16,37953,170315,2019-2020,3.0,5.0,Экзамен,Выпускная квалификационная работа,37953,3,40.04.01,Юриспруденция
101,46150,176649,2019-2020,3.0,5.0,Экзамен,Процессы резания и режущий инструмент,46150,4,15.03.05,Конструкторско-технологическое обеспечение маш...
114,303174,164763,2018-2019,3.0,6.0,Экзамен,Гигиена,303174,4,31.05.01,Лечебное дело
130,283944,120814,2018-2019,3.0,5.0,Дифференцированный зачет,Психолого-педагогическое сопровождение физичес...,283944,5,44.03.01,Педагогическое образование
159,239711,176595,2019-2020,3.0,5.0,Дифференцированный зачет,Схемотехника аналоговых электронных устройств,239711,4,11.03.03,Конструирование и технология электронных средств
...,...,...,...,...,...,...,...,...,...,...,...
104971,35579,162099,2018-2019,3.0,6.0,Дифференцированный зачет,Практика производственная: практика по получен...,35579,5,35.03.06,Агроинженерия
104982,283813,117042,2018-2019,3.0,6.0,Курсовой проект,Силовые агрегаты транспортных и транспортно-те...,283813,3,23.03.03,Эксплуатация транспортно-технологических машин...
104989,360195,85709,2017-2018,3.0,5.0,Курсовой проект,Архитектура зданий,360195,4,08.03.01,Строительство
105033,11220,173643,2019-2020,3.0,5.0,Курсовой проект,Тепломассообменное оборудование предприятий,11220,4,13.03.01,Теплоэнергетика и теплотехника
105048,211556,178332,2019-2020,3.0,5.0,Дифференцированный зачет,Инфекционные болезни,211556,4,31.05.03,Стоматология

In [166]:
# 8

d = {'Пол': []}
for i in range(studs_info_csv.shape[0]):
  d['Пол'].append(0  if (studs_info_csv.loc[i]['Пол']=='М') else  1)

studs_info_csv_intGender = pandas.DataFrame(d)

studs_info_csv.drop(['Пол'], axis=1, inplace=True)
studs_info_csv = pandas.concat([studs_info_csv,studs_info_csv_intGender],axis=1)
studs_info_csv
# d = {'Пол':[]}
# d['Пол'].append( 0  if studs_info_csv.loc[0]['Пол']=='М' else  1)
# d
# studs_info_csv.shape[0]/2
# studs_info_csv

,STD_ID,number,Статус,Дата выпуска,Категория обучения,Форма обучения,Шифр,направление (специальность),,Образование,Дата выдачи,Что именно закончил,Пол
0,99136,13951.0,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2629.0,СР,2013-06-26 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,1
1,99112,13998.0,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,8240.0,СР,2012-06-23 00:00:00,"МОУ СОШ N 2, ПЕСТОВО",1
2,99109,13999.0,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2314.0,СР,2013-06-25 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,1
3,99125,13953.0,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2345.0,СР,2013-06-23 00:00:00,"Гимназия ""ГАРМОНИЯ""",1
4,100676,13950.0,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2650.0,СР,2012-06-29 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5461,100678,978.0,СТ,NaN,БП,Д,31.05.01,Лечебное дело,2388.0,СР,2013-06-21 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,1
5462,100663,1021.0,СТ,NaN,ДОГ,Д,31.05.01,Лечебное дело,2554.0,СР,2013-06-27 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,1
5463,191630,6447.0,СТ,NaN,ДОГ,Д,31.05.01,Лечебное дело,6692.0,СР,2014-05-31 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,1
5464,191625,3765.0,СТ,NaN,ДОГ,Д,31.05.01,Лечебное дело,NaN,NaN,NaN,NaN,1
5465,194978,5245.0,СТ,NaN,ДОГ,Д,31.05.01,Лечебное дело,NaN,NaN,NaN,NaN,1

In [169]:
# 9

inf_ekz = train[train['дисциплина']=='Информатика'][train['аттестация']=='Экзамен']
print(inf_ekz.shape[0], inf_ekz['mark'].sum()/inf_ekz.shape[0])

60 4.6

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  This is separate from the ipykernel package so we can avoid doing imports until