# Домашнее задание

В домашнем задании вам необходимо рассмтреть данные с олимпиады НТИ по профилю "Исскусственный интеллект" за 2019-2020 год.

Задачу можно найти по ссылке:

https://www.kaggle.com/c/onti-students-performance/data

## **Как загрузить данные в Google Colab?**

1. Из Github (файлы <25 МБ)
2. С локального диска
3. С Google Диска

In [ ]:
# Github
# 1. Нажмите на файл с данными, которые хотите подключить
# 2. Нажмите "Raw"
# 3. Скопируйте ссылку открывшейся старницы
import pandas as pd

url = 'https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/X_train.csv'
df1 = pd.read_csv(url)

df1.head()

,Unnamed: 0,STD_ID,НАПРАВЛЕНИЕ,ГОД,КУРС,СЕМЕСТР,АТТЕСТАЦИЯ,ДИСЦИПЛИНА
0,51081,175711,38.03.02 Менеджмент,2018-2019,2.0,4.0,Экзамен,Маркетинг
1,72921,100647,31.05.01 Лечебное дело,2015-2016,3.0,5.0,Экзамен,"Пропедевтика внутренних болезней, лучевая диаг..."
2,96438,199311,31.05.03 Стоматология,2019-2020,1.0,1.0,Экзамен,Химия
3,273044,162002,38.03.02 Менеджмент,2017-2018,2.0,3.0,Экзамен,Статистика
4,371309,108384,31.05.01 Лечебное дело,2018-2019,5.0,9.0,Экзамен,Педиатрия

In [2]:
# С локального компьютера

from google.colab import files
uploaded = files.upload()

In [ ]:
studs_info = pd.read_csv('studs_info.csv')
X_train = pd.read_csv('X_train.csv')
y_train = pd.read_csv('y_train.csv')
zachety = pd.read_csv('zachety.csv')

## Вариант 1.

Кто делает:
1. Анохин Георгий Александрович
2. Георгиев Денис Дмитриевич 
3. Горячев Иван Сергеевич
4. Даниярбек уулу Нурбол
5. Дорохов Матвей Дмитриевич 
6. Зайцев Егор Андреевич

1. Посмотреть размерность дата фреймов.
2. Соедить два датафрейма X_train и y_train в один train по индексам.
3. Посчитать пропуски в получившемся датафрейме train.
4. Посчитать сколько раз встречается каждая специальность в колонке studs_info['направление (специальность)'].
5. Создать новый датафрейм из studs_info, в котором будут только женщины с лечебного дела.
6. Разложить колонку "Дата выпуска" на три: Год выпуска, Месяц выпуска, День выпуска.
7. Посчитать сколько уникальных значений в колонке studs_info['Категория обучения'].
8. Заменить в колонке studs_info['Категория обучения'] все строковые категории на числовые.
9. Удалить ненужную на ваш вгляд колонку из датафрейма studs_info.
10. Посчитать сколько мужчин выпустились 2019-08-31.

In [81]:
import pandas as pd
import numpy as np

x_train = pd.read_csv('https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/X_train.csv')
y_train = pd.read_csv('https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/y_train.csv')
studs_info = pd.read_csv('https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/studs_info.csv')
zachety = pd.read_csv('https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/zachety.csv')

In [82]:
x_train.head()

,Unnamed: 0,STD_ID,НАПРАВЛЕНИЕ,ГОД,КУРС,СЕМЕСТР,АТТЕСТАЦИЯ,ДИСЦИПЛИНА
0,51081,175711,38.03.02 Менеджмент,2018-2019,2.0,4.0,Экзамен,Маркетинг
1,72921,100647,31.05.01 Лечебное дело,2015-2016,3.0,5.0,Экзамен,"Пропедевтика внутренних болезней, лучевая диаг..."
2,96438,199311,31.05.03 Стоматология,2019-2020,1.0,1.0,Экзамен,Химия
3,273044,162002,38.03.02 Менеджмент,2017-2018,2.0,3.0,Экзамен,Статистика
4,371309,108384,31.05.01 Лечебное дело,2018-2019,5.0,9.0,Экзамен,Педиатрия

In [83]:
y_train.head()

    index  mark
0   51081     5
1   72921     5
2   96438     5
3  273044     4
4  371309     3

In [84]:
zachety.head()

,Unnamed: 0,STD_ID,НАПРАВЛЕНИЕ,ГОД,КУРС,СЕМЕСТР,АТТЕСТАЦИЯ,ДИСЦИПЛИНА
0,0,99136,31.05.01 Лечебное дело,2013-2014,1.0,1.0,Зачет,Психология
1,1,99112,31.05.01 Лечебное дело,2013-2014,1.0,1.0,Зачет,Психология
2,2,99109,31.05.01 Лечебное дело,2013-2014,1.0,1.0,Зачет,Психология
3,3,99125,31.05.01 Лечебное дело,2013-2014,1.0,1.0,Зачет,Психология
4,4,100676,31.05.01 Лечебное дело,2013-2014,1.0,1.0,Зачет,Психология

In [85]:
studs_info.head()

,STD_ID,number,Пол,Статус,Дата выпуска,Категория обучения,Форма обучения,Шифр,направление (специальность),,Образование,Дата выдачи,Что именно закончил
0,99136,13951.0,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2629.0,СР,2013-06-26 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
1,99112,13998.0,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,8240.0,СР,2012-06-23 00:00:00,"МОУ СОШ N 2, ПЕСТОВО"
2,99109,13999.0,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2314.0,СР,2013-06-25 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
3,99125,13953.0,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2345.0,СР,2013-06-23 00:00:00,"Гимназия ""ГАРМОНИЯ"""
4,100676,13950.0,М,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2650.0,СР,2012-06-29 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА

In [86]:
print(x_train.shape)
print(y_train.shape)
print(zachety.shape)
print(studs_info.shape)

(105058, 8)
(105058, 2)
(133223, 8)
(5466, 13)

# ----------------------------------------------------------------------------

In [87]:
train = pd.concat([x_train, y_train], axis=1)
train.head()

,Unnamed: 0,STD_ID,НАПРАВЛЕНИЕ,ГОД,КУРС,СЕМЕСТР,АТТЕСТАЦИЯ,ДИСЦИПЛИНА,index,mark
0,51081,175711,38.03.02 Менеджмент,2018-2019,2.0,4.0,Экзамен,Маркетинг,51081,5
1,72921,100647,31.05.01 Лечебное дело,2015-2016,3.0,5.0,Экзамен,"Пропедевтика внутренних болезней, лучевая диаг...",72921,5
2,96438,199311,31.05.03 Стоматология,2019-2020,1.0,1.0,Экзамен,Химия,96438,5
3,273044,162002,38.03.02 Менеджмент,2017-2018,2.0,3.0,Экзамен,Статистика,273044,4
4,371309,108384,31.05.01 Лечебное дело,2018-2019,5.0,9.0,Экзамен,Педиатрия,371309,3

In [88]:
train.isna().sum()

Unnamed: 0     0
STD_ID         0
НАПРАВЛЕНИЕ    0
ГОД            0
КУРС           0
СЕМЕСТР        0
АТТЕСТАЦИЯ     0
ДИСЦИПЛИНА     0
index          0
mark           0
dtype: int64

In [89]:
studs_info['направление (специальность)'].value_counts()

Лечебное дело                                                                870
Юриспруденция                                                                462
Стоматология                                                                 452
Педагогическое образование (с двумя профилями подготовки)                    369
Педагогическое образование                                                   279
Экономика                                                                    226
Строительство                                                                214
Менеджмент                                                                   184
Лингвистика                                                                  136
Специальное (дефектологическое) образование                                  131
Теплоэнергетика и теплотехника                                               126
Журналистика                                                                 118
Конструкторско-технологическое обеспечение машиностроительных производств    115
Фармация                                                                     104
Агроинженерия                                                                100
Конструирование и технология электронных средств                              97
Информатика и вычислительная техника                                          95
Управление персоналом                                                         88
Архитектура                                                                   87
Эксплуатация транспортно-технологических машин и комплексов                   86
Психология                                                                    80
Дизайн                                                                        78
Землеустройство и кадастры                                                    74
Зоотехния                                                                     73
Дизайн архитектурной среды                                                    72
Технология производства и переработки сельскохозяйственной продукции          63
Лесное дело                                                                   61
Филология                                                                     55
Агрономия                                                                     52
Биология                                                                      50
Фундаментальная и прикладная химия                                            48
История                                                                       45
Технология художественной обработки материалов                                44
Государственное и муниципальное управление                                    44
Радиотехника                                                                  40
Электроника и наноэлектроника                                                 36
Культурология                                                                 36
Прикладная математика и информатика                                           35
Экология и природопользование                                                 32
География                                                                     32
Психолого-педагогическое образование                                          30
Философия                                                                     19
Мехатроника и робототехника                                                   18
Сестринское дело                                                               9
Name: направление (специальность), dtype: int64

In [90]:
studs_info_1 = studs_info[(studs_info['направление (специальность)'] == 'Лечебное дело') & (studs_info['Пол'] == 'Ж')]
studs_info_1.head()

,STD_ID,number,Пол,Статус,Дата выпуска,Категория обучения,Форма обучения,Шифр,направление (специальность),,Образование,Дата выдачи,Что именно закончил
0,99136,13951.0,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2629.0,СР,2013-06-26 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
1,99112,13998.0,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,8240.0,СР,2012-06-23 00:00:00,"МОУ СОШ N 2, ПЕСТОВО"
2,99109,13999.0,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2314.0,СР,2013-06-25 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
3,99125,13953.0,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2345.0,СР,2013-06-23 00:00:00,"Гимназия ""ГАРМОНИЯ"""
5,99099,13959.0,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,8800.0,СР,2013-06-21 00:00:00,"МОУ СОШ (полная), ХОЛМ"

In [91]:
def get_date(row, q):
  if row['Дата выпуска'] is np.nan:
    return np.nan
  return str(row['Дата выпуска']).split("-")[q]


studs_info['Год выпуска'] = studs_info.apply(lambda row: get_date(row, 0), axis=1)
studs_info['Месяц выпуска'] = studs_info.apply(lambda row: get_date(row, 1), axis=1)
studs_info['День выпуска'] = studs_info.apply(lambda row: get_date(row, 2), axis=1)


studs_info.head()

,STD_ID,number,Пол,Статус,Дата выпуска,Категория обучения,Форма обучения,Шифр,направление (специальность),,Образование,Дата выдачи,Что именно закончил,Год выпуска,Месяц выпуска,День выпуска
0,99136,13951.0,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2629.0,СР,2013-06-26 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,2019,08,31
1,99112,13998.0,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,8240.0,СР,2012-06-23 00:00:00,"МОУ СОШ N 2, ПЕСТОВО",2019,08,31
2,99109,13999.0,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2314.0,СР,2013-06-25 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,2019,08,31
3,99125,13953.0,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2345.0,СР,2013-06-23 00:00:00,"Гимназия ""ГАРМОНИЯ""",2019,08,31
4,100676,13950.0,М,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2650.0,СР,2012-06-29 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,2019,08,31

In [92]:
ar = studs_info['Категория обучения'].unique()
print(ar)
print(f"Кол-во уникальных значений в 'Категория обучения' >>> {len(ar)}")
print("Кол-во уникальных (не нулевых) значений в 'Категория обучения' >>> ", end="")

for el in ar:
  if el is np.nan:
    print(len(ar) - 1)
    break
else:
  print(len(ar))

['БП' 'ДОГ' nan]
Кол-во уникальных значений в 'Категория обучения' >>> 3
Кол-во уникальных (не нулевых) значений в 'Категория обучения' >>> 2

In [93]:
ar = np.append(ar, [None])
m = {ar[i]: i for i in range(len(ar))}

studs_info['Категория обучения'] = studs_info.apply(lambda row: m[row['Категория обучения']], axis=1)
print(studs_info['Категория обучения'].unique())
(studs_info.head())

[0 1 2]

,STD_ID,number,Пол,Статус,Дата выпуска,Категория обучения,Форма обучения,Шифр,направление (специальность),,Образование,Дата выдачи,Что именно закончил,Год выпуска,Месяц выпуска,День выпуска
0,99136,13951.0,Ж,ВЫП,2019-08-31,0,Д,31.05.01,Лечебное дело,2629.0,СР,2013-06-26 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,2019,08,31
1,99112,13998.0,Ж,ВЫП,2019-08-31,0,Д,31.05.01,Лечебное дело,8240.0,СР,2012-06-23 00:00:00,"МОУ СОШ N 2, ПЕСТОВО",2019,08,31
2,99109,13999.0,Ж,ВЫП,2019-08-31,0,Д,31.05.01,Лечебное дело,2314.0,СР,2013-06-25 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,2019,08,31
3,99125,13953.0,Ж,ВЫП,2019-08-31,0,Д,31.05.01,Лечебное дело,2345.0,СР,2013-06-23 00:00:00,"Гимназия ""ГАРМОНИЯ""",2019,08,31
4,100676,13950.0,М,ВЫП,2019-08-31,0,Д,31.05.01,Лечебное дело,2650.0,СР,2012-06-29 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,2019,08,31

In [94]:
studs_info.drop("Дата выпуска", axis=1, inplace=True)
studs_info

,STD_ID,number,Пол,Статус,Категория обучения,Форма обучения,Шифр,направление (специальность),,Образование,Дата выдачи,Что именно закончил,Год выпуска,Месяц выпуска,День выпуска
0,99136,13951.0,Ж,ВЫП,0,Д,31.05.01,Лечебное дело,2629.0,СР,2013-06-26 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,2019,08,31
1,99112,13998.0,Ж,ВЫП,0,Д,31.05.01,Лечебное дело,8240.0,СР,2012-06-23 00:00:00,"МОУ СОШ N 2, ПЕСТОВО",2019,08,31
2,99109,13999.0,Ж,ВЫП,0,Д,31.05.01,Лечебное дело,2314.0,СР,2013-06-25 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,2019,08,31
3,99125,13953.0,Ж,ВЫП,0,Д,31.05.01,Лечебное дело,2345.0,СР,2013-06-23 00:00:00,"Гимназия ""ГАРМОНИЯ""",2019,08,31
4,100676,13950.0,М,ВЫП,0,Д,31.05.01,Лечебное дело,2650.0,СР,2012-06-29 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,2019,08,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5461,100678,978.0,Ж,СТ,0,Д,31.05.01,Лечебное дело,2388.0,СР,2013-06-21 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,NaN,NaN,NaN
5462,100663,1021.0,Ж,СТ,1,Д,31.05.01,Лечебное дело,2554.0,СР,2013-06-27 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,NaN,NaN,NaN
5463,191630,6447.0,Ж,СТ,1,Д,31.05.01,Лечебное дело,6692.0,СР,2014-05-31 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,NaN,NaN,NaN
5464,191625,3765.0,Ж,СТ,1,Д,31.05.01,Лечебное дело,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5465,194978,5245.0,Ж,СТ,1,Д,31.05.01,Лечебное дело,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [95]:
# М 2019-08-31
df = studs_info[(studs_info['Год выпуска'] == '2019') & (studs_info['Месяц выпуска'] == '08') &
                (studs_info['День выпуска'] == '31') & (studs_info['Пол'] == 'М')]

f"2019-08-31 Выпустилось {len(df)} мужчин"

'2019-08-31 Выпустилось 81 мужчин'